### ISSUE TITLE
Build pipeline

### ISSUE THREAD

**Issue by karelhala** [ManageIQ/catalog-ui#130]
There needs to be 2 different build pipelines for `beta` and `stable` environments and when promoting different branches correct pipeline needs to be selected
* when promoting to `ci-beta`, `qa-beta` and `prod-beta` beta build has to be ran
* when promoting to `ci-stable`, `qa-stable` and `prod-stable` stable build has to be ran

Which build to pick up can be set by env variable.

**Comment by karelhala** [comment]
ping @Fryguy

**Comment by Fryguy** [comment]
@karelhala Can you explain what you mean by beta pointing to stable? Release wise, the build process doesn't care about beta or stable. In other words, the build pipeline we have in place already does this. We just happen to release to beta and stable simultaneously at the moment, but they are completely separate Travis runs.  Is this what the rest of the changes in your original PR were doing? If so, can you just make a PR with those changes?

**Comment by Fryguy** [comment]
@karelhala In looking through your PR changes, it seems most was refactoring, and the actual change was that the "master" branch wasn't in the list of "beta" branches.  I threw a quick PR that just adds that one line to unstick this particular issue.

I do like the rest of your refactorings, particularly if they match what's in insights-frontend-common, so if you could make a PR with the refactorings I would appreciate that.

**Comment by karelhala** [comment]
@Fryguy the problem here is tthat if you are pushing to `*-beta` branch some variable needs to be set (common script checks branch on which the build was started) and build in different way. I will create PR with refactoring stuff, but I think that you will have to update pormoe script to check if it is running beta build or not. You can check in [RedHatInsights/catalog-static-deploy/blob/ci-beta/index.html](https://github.com/RedHatInsights/catalog-static-deploy/blob/ci-beta/index.html) that `src="/apps/catalog..."`  which is incorrect and it should be `src="/beta/apps/catalog..."`. In the closed PR I wanted to split push to beta branhces from master and to stable branches from master-stable because that is how some apps are doing it.

**Comment by Fryguy** [comment]
The only thing that was missing was that "master" itself wasn't in the list of beta branches. #131 added that, and after merged all of those paths look correct...

ci-beta - https://github.com/RedHatInsights/catalog-static-deploy/blob/ci-beta/index.html#L11
qa-beta - https://github.com/RedHatInsights/catalog-static-deploy/blob/qa-beta/index.html#L11
ci-stable - https://github.com/RedHatInsights/catalog-static-deploy/blob/ci-stable/index.html#L11
qa-stable - https://github.com/RedHatInsights/catalog-static-deploy/blob/qa-stable/index.html#L11

**Comment by karelhala** [comment]
Oh okay, nice! So this issue can be closed, thanks for the update.
