### ISSUE TITLE
Not able to scroll down the page and see the content, after trying to create portfolio

### ISSUE THREAD

**Issue by hstastna** [ManageIQ/catalog-ui#14]
**What:**
There is a problem in the UI, after trying to create a new Portfolio (no matter if you submit or not):
the scrollbar disappears => it is not possible to scroll down the page, so the user is not able to see
the rest of Portfolios' list in left menu (if there are more Portfolios) or anything else in the page.

**Steps to reproduce:**
1. While displaying platform items, hover on some and click on _Add Portfolio_
=> the scrollbar disappears! 

**Additional info:**
I was able to recreate always, tried in Firefox, also Chrome, Chromium browsers - the same result.
No matter if you finish adding a new portfolio or not, scrolling is not possible anymore.
Refreshing the page fixes the problem.

---
Platform items, before creating a protfolio (scrolling works well):
![normal](https://user-images.githubusercontent.com/13417815/48625671-263f5200-e9b0-11e8-8302-89c251112528.png)

Creating a new portfolio (scrollbar not present anymore!):
![creating](https://user-images.githubusercontent.com/13417815/48625713-440cb700-e9b0-11e8-93a4-2cac11c487ac.png)

No matter if canceling adding portfolio or creating the new one (scrollbar still not present, closing the alert has no impact):
![cancel](https://user-images.githubusercontent.com/13417815/48625764-6999c080-e9b0-11e8-8e49-d3f48d9d269f.png)

**Comment by gmcculloug** [comment]
Issue has been resolved in the latest builds.
