### ISSUE TITLE
Orders page for failed orders ( and highlighted step for all orders )

### ISSUE THREAD

**Issue by syncrou** [ManageIQ/catalog-ui#173]
<img width="1346" alt="Red_Hat_Insights___Catalog" src="https://user-images.githubusercontent.com/697347/56687438-49c7a080-66a4-11e9-8f8a-135ac917bd34.png">

**Comment by syncrou** [comment]
For failed orders we would like to see the 'x' at the last item that didn't complete. The same is true with the blue highlight on the step numbers.

**Comment by Hyperkid123** [comment]
Ok i got fix for the highlight position but i need some clarification for the failed step. Correct me if i am wrong but the first step status is tied to the order item right? So if that is true then there should be only one status icons (like in the original picture).

**Comment by Hyperkid123** [comment]
Resolved by #179
