### ISSUE TITLE
Expired JWT Token

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/catalog-ui#176]
Should we recommend in the message that the user needs to logout and re-login?

![Screen Shot 2019-04-24 at 5 37 27 PM](https://user-images.githubusercontent.com/6452699/56695824-feb78880-66b7-11e9-8416-84710ee7131e.png)

**Comment by Hyperkid123** [comment]
@mkanoor this is platform issue and cannot be fixed from our side. I could possibly add interceptor that will redirect you to the login screen but is mostly a hack. We don't have access to authorization service from catalog.

**Comment by mkanoor** [comment]
@Hyperkid123 OK.
This is the other popup is this also handled by platform

![Screen Shot 2019-04-25 at 12 02 21 PM](https://user-images.githubusercontent.com/6452699/56750627-3115c400-6752-11e9-92ba-d0f7cd358a55.png)

**Comment by Hyperkid123** [comment]
@mkanoor there is notification component with middleware that looks at requests and catches error requests and then shows the error message from API.
