### ISSUE TITLE
Time missing in the Order Stages

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/catalog-ui#177]
Only date is visible in the Order Stages even though the heading says "Date & Time"

![Screen Shot 2019-04-24 at 5 38 24 PM](https://user-images.githubusercontent.com/6452699/56695880-2d356380-66b8-11e9-9308-ac90f8205818.png)

**Comment by gmcculloug** [comment]
@sbuenafe-rh I recall you said this should be relative date/time and on hover over it should display UTC.  Is that still the plan?

**Comment by sbuenafe-rh** [comment]
@gmcculloug yes, the guidance is relative date/time with tooltip with precise date and UTC time. We do display the relative time for when it was ordered, and when the order was updated in the row. I just brought forward the precise date/time for the steps -- in thinking forward that our event log will have the precise timestamps.
