### ISSUE TITLE
UI hangs when a non privileged user "Creates Portfolio"

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/catalog-ui#181]
If a user doesn't have access to create Portfolios the REST API returns a 403 Forbidden
```
HTTP/1.1 403 Forbidden

{"message":"Write access not authorized for Portfolio"}
```

This causes the UI to keep spinning.
If you switch to a privileged user you can create the portfolio successfully.

**Comment by Hyperkid123** [comment]
Resolved by #184
