### ISSUE TITLE
Orders page for in progress orders

### ISSUE THREAD

**Issue by syncrou** [ManageIQ/catalog-ui#190]
<img width="1371" alt="Screen Shot 2019-04-30 at 1 36 34 PM" src="https://user-images.githubusercontent.com/697347/56981536-1a55df80-6b4d-11e9-8750-443178bcc6e7.png">

We would like the blue highlight to move inline with the current step in progress. This change will allow the In progress orders to match how a failed order looks.

<img width="1371" alt="Screen_Shot_2019-04-30_at_1_36_34_PM" src="https://user-images.githubusercontent.com/697347/56981657-702a8780-6b4d-11e9-87a1-9bc7d94d06e3.png">

**Comment by Hyperkid123** [comment]
Fixed by #194
