### ISSUE TITLE
During a refresh of the Order Page we get an error

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/catalog-ui#191]
![Screen Shot 2019-04-30 at 4 32 28 PM](https://user-images.githubusercontent.com/6452699/56991460-b55ab380-6b65-11e9-8605-bc4021095f85.png)

**Comment by gmcculloug** [comment]
@mkanoor Please retest.  If this is still an issue let us know what env you are hitting this on.  Also, recommend that you clear cookies as well.

**Comment by mkanoor** [comment]
Works as documented
